name: Daily Tennis Digest
on:
  schedule:
    - cron: "30 19 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python scripts/push_today.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOURNAMENT_URL: ${{ secrets.TOURNAMENT_URL }}
          TZ: Europe/Moscow
          # TITLE_OVERRIDE: "Париж, 1-й/2-й круг, ATP 1000"
